# Test Infrastructure for CLI Output Testing

#' Test CLI Abort Errors
#'
#' Helper function to test errors generated by cli::cli_abort()
#' without requiring exact message format matching.
#'
#' @param object Expression that should throw an error
#' @param ... Additional arguments passed to expect_error
#'
#' @examples
#' \dontrun{
#' expect_cli_abort({
#'   build_conditions(design = "invalid", condition_values = list(), static_values = list())
#' })
#' }
#'
expect_cli_abort <- function(object, ...) {
  testthat::expect_error(object, class = "rlib_error_3_0", ...)
}

#' Test CLI Warnings
#'
#' Helper function to test warnings generated by cli::cli_warn()
#' without requiring exact message format matching.
#'
#' @param object Expression that should generate a warning
#' @param ... Additional arguments passed to expect_warning
#'
#' @examples
#' \dontrun{
#' expect_cli_warn({
#'   # some code that generates a cli warning
#' })
#' }
#'
expect_cli_warn <- function(object, ...) {
  testthat::expect_warning(object, class = "rlib_warning_3_0", ...)
}

#' Capture CLI Output for Testing
#'
#' Captures output from CLI functions for testing purposes.
#' Useful for testing print methods and status messages.
#'
#' @param expr Expression to evaluate and capture output from
#'
#' @return Character vector with captured output
#'
#' @examples
#' \dontrun{
#' output <- capture_cli({
#'   print(my_rctbp_model)
#' })
#' expect_true(any(grepl("Model name", output)))
#' }
#'
capture_cli <- function(expr) {
  # Temporarily switch to non-interactive mode to get consistent output
  old_interactive <- options(rlang_interactive = FALSE)
  on.exit(options(old_interactive))

  # Capture both stdout and messages
  utils::capture.output(
    {
      result <- tryCatch(
        {
          force(expr)
          NULL
        },
        message = function(m) {
          message(m$message, appendLF = FALSE)
          NULL
        }
      )
    },
    type = "output"
  )
}

#' Test That Output Contains Expected Content
#'
#' Convenience function to test that captured output contains expected strings.
#'
#' @param expr Expression that generates output
#' @param expected Character vector of strings that should appear in output
#' @param mode Output mode to use ("cli" or "markdown")
#'
#' @examples
#' \dontrun{
#' expect_output_contains(
#'   print(my_model),
#'   c("Model name", "Backend")
#' )
#' }
#'
expect_output_contains <- function(expr, expected, mode = "cli") {
  old_mode <- set_output_mode(mode)
  on.exit(set_output_mode(old_mode))

  output <- capture_cli(expr)
  output_text <- paste(output, collapse = "\n")

  for (exp in expected) {
    testthat::expect_true(
      grepl(exp, output_text, fixed = TRUE),
      info = sprintf("Expected to find '%s' in output", exp)
    )
  }
}

#' Test Markdown Output
#'
#' Test that output can be generated in markdown mode and contains expected elements.
#'
#' @param object Object to print
#' @param expected Character vector of markdown elements to check for
#'
#' @examples
#' \dontrun{
#' expect_markdown_output(
#'   my_model,
#'   c("##", "**Model name**")
#' )
#' }
#'
expect_markdown_output <- function(object, expected) {
  withr::with_options(
    list(rctbayespower.output_mode = "markdown"),
    {
      output <- capture_cli(print(object))
      output_text <- paste(output, collapse = "\n")

      for (exp in expected) {
        testthat::expect_true(
          grepl(exp, output_text, fixed = FALSE),
          info = sprintf("Expected to find markdown element '%s' in output", exp)
        )
      }
    }
  )
}

#' Setup and Teardown for Output Mode Tests
#'
#' Ensures output mode and verbosity settings are reset after tests.
#'
#' @examples
#' \dontrun{
#' test_that("output mode switching works", {
#'   withr::local_options(list(
#'     rctbayespower.output_mode = "cli",
#'     rctbayespower.silent = 1
#'   ))
#'   # ... tests ...
#' })
#' }
#'
NULL
